#!/usr/bin/env bash
# This script iterates 'To infinity and beyond' with a sleep of 2 between eath iteration
trap 'echo "I am invincible!!!"' SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
