#!/usr/bin/env bash
# This script is doing these: 1: Creates the file /tmp/myscript.pid containing its PID  / 2: Displays To infinity and beyond indefinitely / 3: Displays I hate the kill command when receiving a SIGTERM signal / 4: Displays Y U no love me?! when receiving a SIGINT signal / 5: Deletes the file /tmp/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal.

echo $$ > /tmp/myscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /tmp/myscript.pid && kill -9 $(pgrep bash)' SIGQUIT
while true
do
    echo "Ti infinity and beyond"
    sleep 2
done
